### ISSUE TITLE
Unable to test validation

### ISSUE THREAD

**Issue by base64bits** [Slamdunk/php-validatore-fattura-elettronica#1]
Hi, I am trying to test your module with your instructions: 

```php
use SlamFatturaElettronica\Validator;

$feValidator = new Validator();
$feValidator->assertValidXml('xml data goes here');
```

But I get error

```
Fatal error: Uncaught Error: Class 'SlamFatturaElettronica\Validator' not found in /Users/home/Sites/xml-val/test.php
```

Any help will be greatly appreciated, I am trying to incorporate a XML validator for Costa Rica Factura Electrónica.

**Comment by Slamdunk** [comment]
Hi, it should be noted that this only works for **Italian** standards, as the [XSD](https://github.com/Slamdunk/php-validatore-fattura-elettronica/blob/master/xsd/Schema_VFPR12.xsd) used explicitely reports gov.it references.

However, you must use composer autoload standard as described in the compsoer documentation:
https://getcomposer.org/doc/01-basic-usage.md#autoloading

Thus, using `require __DIR__ . '/vendor/autoload.php';` at the start of your script.

**Comment by base64bits** [comment]
Thanks for taking the time to explain, I am new to programming and forgot that part, grazie mille!
