### ISSUE TITLE
Element 'PECDestinatario': [facet 'pattern'] The value 'test@pec-prova.it' is not accepted by the pattern

### ISSUE THREAD

**Issue by ToX82** [Slamdunk/php-validatore-fattura-elettronica#11]
Dopo l'ultimo aggiornamento si presenta un problema nella validazione di indirizzi PEC. L'errore generato è 

    DOMDocument::schemaValidateSource(): Element 'PECDestinatario': [facet 'pattern'] The value 'test@pec-prova.it' is not accepted by the pattern '([!#-'*+/-9=?A-Z^-~-]+(\\.[!#-'*+/-9=?A-Z^-~-]+)*|"(\\[\\]!#-[^-~ \\t]|(\\\\[\\t -~]))+")@([!#-'*+/-9=?A-Z^-~-]+(\\.[!#-'*+/-9=?A-Z^-~-]+)*|\\[[\\t -Z^-~]*\\])'.

Sembra che il problema sia il trattino `-` nell'indirizzo

**Comment by Slamdunk** [comment]
Il trattivo viene validato; mi sembra che il problema sia che la pec così costruita è minuscola, mentre la regex la richiede tutta maiuscola. Con la versione `1.2` andava bene perché la regex era più lasca:

https://github.com/Slamdunk/php-validatore-fattura-elettronica/blob/d619aa800f50a71c641aa102a1c181568ef016d7/xsd/Schema_VFPR12.xsd#L1259-L1265

**Comment by ToX82** [comment]
In effetti è vero, il trattino sembra venire validato dalla regex.
Ho provato però a modificare l'indirizzo pec e metterlo in maiuscolo, ma ottengo questo

`Element 'PECDestinatario': [facet 'pattern'] The value 'TEST@PEC-PROVA.IT' is not accepted by the pattern`

Se tolgo il trattino il problema si risolve

**Comment by Slamdunk** [comment]
Hanno fatto una cavolata: `[!#-'*+/-9=?A-Z^-~-]` in vari contesti come il `\DOMDocument::schemaValidateSource` che usa PHP si traduce in "_tutti i caratteri tranne `-`_" perché si sono dimenticati di fare l'escape del caret `^`.

A questo punto mi vien voglia di usare il precedente pattern, e demandare all'utente la validazione della PEC.

**Comment by ToX82** [comment]
Ottimo, sì mi sembra l'idea migliore per ora. Farò comunque una segnalazione a Sogei per risolvere il problema nello schema visto che è quello ufficiale

**Comment by TheMule71** [comment]
Considerate anche questo: https://bugs.launchpad.net/lxml/+bug/1909761

Altri motori di re non hanno problemi con le specifiche dello SdI. Se si prova la re dello SdI qui https://regex101.com/ funziona con tutte le varianti (incluso il PHP se si usa ` come delimiter ovviamente). Per funziona intendo che matcha correttamente gli indirizzi contenenti trattini.
