### ISSUE TITLE
Add validation for message files

### ISSUE THREAD

**Issue by aded** [Slamdunk/php-validatore-fattura-elettronica#2]
Hi, thanks for your library! I require it via-composer for invoice validation in [taocomp/php-e-invoice-it](https://github.com/taocomp/php-e-invoice-it) and mention you in Credits of course. :-)

Did you plan validation for message files too ([MessaggiTypes](https://www.fatturapa.gov.it/export/fatturazione/it/normativa/f-3.htm))?

**Comment by Slamdunk** [comment]
Hi, it would indeed be a great addition.
I haven't done it only because I've never needed them yet.

I don't have any ETA however: would you like to create a PR for this? I'd be glad to review it :+1:

**Comment by aded** [comment]
Hi @Slamdunk, I'll try to create a pull request in the next few days (I'm very busy at the moment... :grimacing:).
