### ISSUE TITLE
DOMDocument::schemaValidateSource(): Element 'RiferimentoNormativo'

### ISSUE THREAD

**Issue by MwSpaceLLC** [Slamdunk/php-validatore-fattura-elettronica#4]
Buondies !!! 😁😁
Oggi abbiamo aggiunto dei dati alla fattura XML per Bollo ed esenzione..
Il validator Valida tutti questi campi ?
PS: nel post di prima avevamo fatto un'errore. Ma chiediamo solo conferma
![image](https://user-images.githubusercontent.com/29952045/50969260-2eae9780-14de-11e9-96fb-16db1b5a30f3.png)

Ti riporto i campi che inseriremo: 
![image](https://user-images.githubusercontent.com/29952045/50969362-7e8d5e80-14de-11e9-9048-6cc82e0dfba2.png)

![image](https://user-images.githubusercontent.com/29952045/50969371-877e3000-14de-11e9-9737-b9c32588bcb5.png)

![image](https://user-images.githubusercontent.com/29952045/50969295-45ed8500-14de-11e9-98d0-3fd579405d8e.png)

![image](https://user-images.githubusercontent.com/29952045/50969313-57369180-14de-11e9-80e8-d62f2a3282ae.png)

![image](https://user-images.githubusercontent.com/29952045/50969335-6a496180-14de-11e9-822e-ed5a90723490.png)

![image](https://user-images.githubusercontent.com/29952045/50969457-d7f58d80-14de-11e9-96dc-e2a3b3fc48d4.png)

Dovrebbero esserci tutti. Il documento è stato preso da un gestionale MOLTO utilizzato.
Noi per adesso abbiamo disabilitato la validazione per continuare a generare l'xml.
Se si da un'occhio anche [qui](https://www.fatturapa.gov.it/export/fatturazione/sdi/Specifiche_tecniche_del_formato_FatturaPA_v1.0.pdf), ne parlano di questi campi

**Comment by Slamdunk** [comment]
Ciao, ho bisogno dell'XML originale per effettuare una indagine più accurata (chiaramente con i dati sensibili offuscati).

Comunque posso dirti che:

1. l'XSD usato è creato dall'agenzia delle entrate, questa libreria non fa altro che attuarlo
1. Il link che riporti si riferisce alle specifiche 1.0, mentre le ultime specifiche disponibili sono alla [versione 1.3 del 21 dicembre 2018](https://www.agenziaentrate.gov.it/wps/content/Nsilib/Nsi/Schede/Comunicazioni/Fatture+e+corrispettivi/Fatture+e+corrispettivi+ST/ST+invio+di+fatturazione+elettronica/?page=schedecomunicazioni)

**Comment by MwSpaceLLC** [comment]
Guarda ti carico l'xml 🤣
Il mio è stato (Come al solito) un'errore. ma per essere sicuri che ci siano tutti i campi te lo giro.

```
<?xml version="1.0" encoding="utf-8"?>
<FatturaElettronica xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" versione="FPR12" xmlns="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2">
  <FatturaElettronicaHeader xmlns="">
    <DatiTrasmissione>
      <IdTrasmittente>
        <IdPaese>IT</IdPaese>
        <IdCodice>10209790152</IdCodice>
      </IdTrasmittente>
      <ProgressivoInvio>11</ProgressivoInvio>
      <FormatoTrasmissione>FPR12</FormatoTrasmissione>
      <CodiceDestinatario>0000000</CodiceDestinatario>
    </DatiTrasmissione>
    <CedentePrestatore>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>IT</IdPaese>
          <IdCodice>**********</IdCodice>
        </IdFiscaleIVA>
        <CodiceFiscale>**********</CodiceFiscale>
        <Anagrafica>
          <Denominazione>**********</Denominazione>
        </Anagrafica>
        <RegimeFiscale>RF01</RegimeFiscale>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>VIA FEDERICO FARUFFINI</Indirizzo>
        <NumeroCivico>2</NumeroCivico>
        <CAP>06100</CAP>
        <Comune>Perugia</Comune>
        <Provincia>PG</Provincia>
        <Nazione>IT</Nazione>
      </Sede>
      <Contatti>
        <Telefono>**********</Telefono>
        <Fax>**********</Fax>
        <Email>**********</Email>
      </Contatti>
    </CedentePrestatore>
    <CessionarioCommittente>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>IT</IdPaese>
          <IdCodice>**********</IdCodice>
        </IdFiscaleIVA>
        <CodiceFiscale>**********</CodiceFiscale>
        <Anagrafica>
          <Denominazione>**********</Denominazione>
        </Anagrafica>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>VIA FEDERICO FARUFFINI</Indirizzo>
        <NumeroCivico>2</NumeroCivico>
        <CAP>06129</CAP>
        <Comune>Perugia</Comune>
        <Provincia>PG</Provincia>
        <Nazione>IT</Nazione>
      </Sede>
    </CessionarioCommittente>
  </FatturaElettronicaHeader>
  <FatturaElettronicaBody xmlns="">
    <DatiGenerali>
      <DatiGeneraliDocumento>
        <TipoDocumento>TD01</TipoDocumento>
        <Divisa>EUR</Divisa>
        <Data>2019-01-09</Data>
        <Numero>3/E</Numero>
        <DatiBollo>
          <BolloVirtuale>SI</BolloVirtuale>
          <ImportoBollo>2.00</ImportoBollo>
        </DatiBollo>
        <DatiCassaPrevidenziale>
          <TipoCassa>TC20</TipoCassa>
          <AlCassa>4.00</AlCassa>
          <ImportoContributoCassa>7.20</ImportoContributoCassa>
          <ImponibileCassa>180.00</ImponibileCassa>
          <AliquotaIVA>22.00</AliquotaIVA>
        </DatiCassaPrevidenziale>
        <ImportoTotaleDocumento>228.38</ImportoTotaleDocumento>
        <Arrotondamento>0.00</Arrotondamento>
      </DatiGeneraliDocumento>
    </DatiGenerali>
    <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <Descrizione>SERVIZIO INTEL</Descrizione>
        <Quantita>1.00</Quantita>
        <UnitaMisura>PZ</UnitaMisura>
        <PrezzoUnitario>180.00</PrezzoUnitario>
        <PrezzoTotale>180.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DatiRiepilogo>
        <AliquotaIVA>22.00</AliquotaIVA>
        <ImponibileImporto>187.20</ImponibileImporto>
        <Imposta>41.18</Imposta>
        <EsigibilitaIVA>I</EsigibilitaIVA>
      </DatiRiepilogo>
    </DatiBeniServizi>
    <DatiPagamento>
      <CondizioniPagamento>TP02</CondizioniPagamento>
      <DettaglioPagamento>
        <ModalitaPagamento>MP01</ModalitaPagamento>
        <DataScadenzaPagamento>2019-01-09</DataScadenzaPagamento>
        <ImportoPagamento>228.38</ImportoPagamento>
        <IstitutoFinanziario>UNICREDIT SPA</IstitutoFinanziario>
        <IBAN>**********</IBAN>
        <ABI>**********</ABI>
        <CAB>**********</CAB>
      </DettaglioPagamento>
    </DatiPagamento>
    <Allegati>
      <NomeAttachment>Fattura_2019-3.pdf</NomeAttachment>
      <FormatoAttachment>PDF</FormatoAttachment>
      <DescrizioneAttachment>Fattura_2019-3.pdf</DescrizioneAttachment>
      <Attachment>...</Attachment>
    </Allegati>
  </FatturaElettronicaBody>
</FatturaElettronica>
```

**Comment by Slamdunk** [comment]
Nell'XML che vedo non c'è traccia di uso del campo `RiferimentoFormativo`.

>  Il validator Valida tutti questi campi ?

Come detto, questo validatore usa l'XSD redatto dall'Agenzia delle Entrate, consultabile liberamente qui:

https://www.agenziaentrate.gov.it/wps/file/Nsilib/Nsi/Schede/Comunicazioni/Fatture+e+corrispettivi/Fatture+e+corrispettivi+ST/ST+invio+di+fatturazione+elettronica/ST+Fatturazione+elettronica+-+Schema+VFSM10/Schema_VFSM10.xsd

Ed applicato secondo le specifiche W3C:

https://en.wikipedia.org/wiki/XML_Schema_(W3C)

**Comment by MwSpaceLLC** [comment]
Scusa! Oggi non ci 'chiappo na mazza' 😢
Ho sbagliato ad allegarti l'xml.
CMQ ora ho ben chiaro come funziona il validator.

**mi dispiace per il disagio**. Alex
