### ISSUE TITLE
Metodo getAllExceptions restituisce un array troppo prolisso

### ISSUE THREAD

**Issue by ToX82** [Slamdunk/php-validatore-fattura-elettronica#48]
In seguito alla pull request #43 , ho notato che gli errori vengono riportati in modo più prolisso rispetto a come l'avevo implementato io.

Secondo me l'array dovrebbe contenere solo gli errori effettivamente rilevati, senza stack trace o informazioni sull'eccezione generata. Questo perché gli errori in questo modo risulterebbero """"accettabili"""" anche come informazione da dare all'utente:

    Element 'CodiceDestinatario': [facet 'pattern'] The value '' is not accepted by the pattern '[A-Z0-9]{6,7}'.

Lo stesso errore, nella patch rilasciata, secondo me contiene troppe informazioni per quel tipo di utilizzo:

    SlamFatturaElettronica\Exception\InvalidXsdStructureComplianceException: Element 'CodiceDestinatario': [facet 'pattern'] The value '' is not accepted by the pattern '[A-Z0-9]{6,7}'. in /var/www/gktmanager/vendor/slam/php-validatore-fattura-elettronica/lib/Validator.php:63 Stack trace: #0 [internal function]: SlamFatturaElettronica\Validator::SlamFatturaElettronica\{closure}() #1 /var/www/gktmanager/vendor/slam/php-validatore-fattura-elettronica/lib/Validator.php(63): DOMDocument->schemaValidateSource() #2 /var/www/gktmanager/plugins/exportFE/src/SdiValidator.php(27): SlamFatturaElettronica\Validator->getAllExceptions() #3 /var/www/gktmanager/plugins/exportFE/edit.php(112): Plugins\ExportFE\SdiValidator::valida() #4 /var/www/gktmanager/include/manager.php(245): include('...') #5 /var/www/gktmanager/editor.php(425): include('...') #6 {main}

Può avere senso mantenere separate le logiche, e gestire da una parte gli errori semplici e dall'altra le eccezioni?

**Comment by Slamdunk** [comment]
> Può avere senso mantenere separate le logiche, e gestire da una parte gli errori semplici e dall'altra le eccezioni?

No: `getAllExceptions` restituisce una lista di eccezioni, spetta a te decidere come farle vedere.
Al momento mi sembra che tu stia facendo un _type-casting_ delle eccezioni a stringa, e così ti viene fuori il messaggio lungo.

Se usi il metodo `getMessage()` su ogni eccezione, puoi creare l'array che cerchi, lasciando agli altri utenti la possibilità, se vogliono, si ricavare anche altre informazioni.
