### ISSUE TITLE
[SlamFatturaElettronica\Exception\InvalidXmlStructureException] simplexml_load_string(): namespace error : xmlns:pfx6: 'http://www.example.com/XSD riepilogo_fattura_ordinaria_v1.2_mod.xsd' is not a valid URI

### ISSUE THREAD

**Issue by ToX82** [Slamdunk/php-validatore-fattura-elettronica#6]
Ciao, ho notato un problema quando nell'intestazione della fattura c'è un namespace che contiene uno spazio (mi è capitato più volte di ricevere fatture che lo contenevano, quindi sono passate dal Servizio di Interscambio). Per esempio:

Funziona
`<p:FatturaElettronica ... xmlns:pfx6="http://www.example.com/XSD_riepilogo_fattura_ordinaria_v1.2_mod.xsd" >`

Non funziona
`<p:FatturaElettronica ... xmlns:pfx6="http://www.example.com/XSD riepilogo_fattura_ordinaria_v1.2_mod.xsd" >`

L'errore generato nel secondo caso è `[SlamFatturaElettronica\Exception\InvalidXmlStructureException] simplexml_load_string(): namespace error : xmlns:pfx6: 'http://www.example.com/XSD riepilogo_fattura_ordinaria_v1.2_mod.xsd' is not a valid URI`

Allego due files di esempio

[test_funzionante.txt](https://github.com/Slamdunk/php-validatore-fattura-elettronica/files/3558842/test_funzionante.txt)
[test_non_funzionante.txt](https://github.com/Slamdunk/php-validatore-fattura-elettronica/files/3558843/test_non_funzionante.txt)

**Comment by marcomarsala** [comment]
Secondo la specifica XML 1.0 https://www.w3.org/TR/xml-names/ lo spazio è un carattere consentito:

_The attribute's normalized value MUST be either a URI reference — the namespace name identifying the namespace — or an empty string. The namespace name, to serve its intended purpose, SHOULD have the characteristics of uniqueness and persistence. *It is not a goal that it be directly usable for retrieval of a schema (if any exists)*. Uniform Resource Names [*RFC2141*] is an example of a syntax that is designed with these goals in mind. However, it should be noted that ordinary URLs can be managed in such a way as to achieve these same goals._

RFC2141 pagina 3 diche che lo spazio *non* è fra i caratteri esclusi:

`2.3.2 The other reserved characters`

   `RFC 1630 [2] reserves the characters "/", "?", and "#" for particular`
   `purposes. The URN-WG has not yet debated the applicability and`
   `precise semantics of those purposes as applied to URNs. Therefore,`
   `these characters are RESERVED for future developments.  Namespace`
   `developers SHOULD NOT use these characters in unencoded form, but`
   `rather use the appropriate %-encoding for each character.`

`2.4 Excluded characters`

   `The following list is included only for the sake of completeness.`
   `Any octets/characters on this list are explicitly NOT part of the URN`
   `character set, and if used in an URN, MUST be %encoded:`

   `<excluded> ::= octets 1-32 (1-20 hex) | "\" | """ | "&" | "<"`
                  `| ">" | "[" | "]" | "^" | "`" | "{" | "|" | "}" | "~"`
                  `| octets 127-255 (7F-FF hex)`

   `In addition, octet 0 (0 hex) should NEVER be used, in either`
   `unencoded or %-encoded form.`

   `An URN ends when an octet/character from the excluded character set`
   `(<excluded>) is encountered.  The character from the excluded`
   `character set is NOT part of the URN.` (edited)

**Comment by Slamdunk** [comment]
Purtroppo quel che passa da SDI deve essere considerato valido: siccome lo scopo di tale libreria è soprattutto validare in senso stretto i dati della fattura, sono propenso a ignorare tali errori anche se li sceglieremo puntualmente di volta in volta

**Comment by ToX82** [comment]
Scusa non mi sono spiegato bene io: la fattura è passata da SdI ed è arrivata a noi sul cassetto fiscale. Il validatore lo utilizziamo durante l'operazione che facciamo per caricare la fattura sulla nostra applicazione, ed è lì che si è presentato l'errore.

**Comment by Slamdunk** [comment]
Sì avevo capito: intendo dire che seppure abbia ragione il validatore di questa libreria, dobbiamo comunque considerare valire l'XML perché lo dice SDI che è valido, quindi andrò a gestire il caso specifico affinché non riporti più questo errore, vedi #7

**Comment by Slamdunk** [comment]
Related: https://github.com/OCA/l10n-italy/issues/902

**Comment by Slamdunk** [comment]
In #7 ora do priorità all'XSD: se il documento è valido per l'XSD, ignora eventuali errori XML.
Se è invece assente la validità XSD, ricontrolla anche la validità formale dell'XML.

**Comment by Slamdunk** [comment]
Fix rilasciato in [v1.2-patch20190830.1](https://github.com/Slamdunk/php-validatore-fattura-elettronica/releases/tag/v1.2-patch20190830.1)

**Comment by ToX82** [comment]
Funziona! Ottimo grazie
